# wrangler.toml
[env.production]
vars = { ENVIRONMENT = "production" }

[[kv_namespaces]]
binding = "LMCTFY_KV"
id = "15c67f509d4e46548fb840754d3128bc"
preview_id = "2ff697068ff64deda85350624d557f18"

[env.staging]
vars = { ENVIRONMENT = "staging" }

# [[kv_namespaces]]
# binding = "KV_STORE"
# preview_id = "2ff697068ff64deda85350624d557f18"

[build]
command = ""
cwd = "public"
watch_paths = ["public", "functions"]
