name = "lmctfy-ai"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespace binding for URL storage
[[kv_namespaces]]
binding = "URLS"
id = "56cf72fa04b9404a9c6a978e7c90ad2b"
preview_id = "0fd4b3adef6e4c108804cd50f1d2ea38"

# Routes for custom domain
routes = [
  { pattern = "lmctfy.ai/*", zone_name = "lmctfy.ai" }
]

# Environment variables (if needed)
[vars]
ENVIRONMENT = "production"

# Development settings
[env.development]
name = "lmctfy-ai-dev"
vars = { ENVIRONMENT = "development" }

# Pages configuration
pages_build_output_dir = "./dist"

# Workers Sites configuration for static file serving (keep for worker)
[site]
bucket = "./dist"